Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,6 @@ jobs:
       
       - name: Run action
         run: echo "Running sction... "
+        
+      - name: error
+        run: echo "error"; exit 1
